const { describe, test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

/**
 * Smoketests for the committed Open Waters offline style assets
 * (public/open-waters, generated by scripts/fetch-open-waters-assets.mjs):
 * the style a MapLibre client consumes offline, the sprite sheet its
 * symbol layers draw from, and the glyph ranges its text layers need.
 * All URLs are root-relative so the assets work at whatever address
 * the boat network uses for the Signal K server.
 */

const ASSETS_DIR = path.join(__dirname, "..", "public", "open-waters");
const PLUGIN_STATIC_BASE = "/plugins/signalk-corridor-tile-downloader";

describe("Open Waters offline style assets", () => {
  const style = JSON.parse(
    fs.readFileSync(path.join(ASSETS_DIR, "style.json"), "utf8"),
  );

  test("style.json is a self-contained offline style", () => {
    assert.equal(style.version, 8);
    assert.equal(style.sources.openwaters.type, "vector");
    assert.equal(
      style.sources.openwaters.tiles[0],
      "/signalk/v1/api/resources/charts/passage_cache/{z}/{x}/{y}",
    );
    assert.equal(style.sources.openwaters.minzoom, 0);
    // Native ceiling of the seamap tile set; clients overzoom past it
    assert.equal(style.sources.openwaters.maxzoom, 14);
    // Attribution survives the extraction
    assert.match(style.metadata.attribution, /OpenStreetMap/);
  });

  test("layers reference only the offline source", () => {
    assert.ok(style.layers.length >= 50, "full seamap symbology present");
    const sources = new Set(
      style.layers.filter((l) => "source" in l).map((l) => l.source),
    );
    assert.deepEqual([...sources], ["openwaters"]);
    assert.ok(
      style.layers.some((l) => l.type === "background"),
      "a background layer exists",
    );
  });

  test("sprite entries point at locally hosted sheet files", () => {
    assert.ok(Array.isArray(style.sprite));
    for (const sprite of style.sprite) {
      assert.ok(sprite.url.startsWith(`${PLUGIN_STATIC_BASE}/open-waters/`));
      const base = sprite.url.replace(`${PLUGIN_STATIC_BASE}/open-waters/`, "");
      for (const variant of ["", "@2x"]) {
        for (const ext of ["json", "png"]) {
          const file = path.join(ASSETS_DIR, `${base}${variant}.${ext}`);
          assert.ok(fs.existsSync(file), `${base}${variant}.${ext} committed`);
        }
      }
    }
  });

  test("every referenced fontstack is hosted with glyph ranges", () => {
    const glyphsUrl = style.glyphs;
    assert.ok(glyphsUrl.startsWith(`${PLUGIN_STATIC_BASE}/open-waters/`));
    assert.ok(glyphsUrl.includes("{fontstack}/{range}.pbf"));

    const fontstacks = new Set();
    for (const layer of style.layers) {
      const font = layer.layout?.["text-font"];
      if (Array.isArray(font)) fontstacks.add(font[font.length - 1]);
    }
    assert.ok(fontstacks.size > 0, "symbol layers use text");
    for (const font of fontstacks) {
      const dir = path.join(ASSETS_DIR, "glyphs", font);
      assert.ok(fs.existsSync(dir), `glyphs/${font}/ committed`);
      // First and last ranges of the 0-65535 codepoint space
      for (const range of ["0-255", "65280-65535"]) {
        const file = path.join(dir, `${range}.pbf`);
        assert.ok(
          fs.existsSync(file) && fs.statSync(file).size > 0,
          `glyphs/${font}/${range}.pbf committed`,
        );
      }
    }
  });
});
